package main

import (
	"context"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"strings"
	"testing"
)

func TestRun(t *testing.T) {
	cases := []struct {
		name     string
		filename string
		source   string
		fails    bool
	}{
		{
			name: "test files are checked", filename: "example_test.go",
			source: "package example\nfunc example() {\nm := make(map[string]int)\n\ndelete(m, \"key\")\n}\n",
			fails:  true,
		},
		{
			name: "generated files are skipped", filename: "example.go",
			source: "// Code generated by fixture. DO NOT EDIT.\npackage example\n" +
				"func example() {\nm := make(map[string]int)\n\ndelete(m, \"key\")\n}\n",
		},
		{
			name: "type errors fail the check", filename: "example.go",
			source: "package example\nvar value = missing\n",
			fails:  true,
		},
	}
	for _, scenario := range cases {
		t.Run(scenario.name, func(t *testing.T) {
			t.Chdir(t.TempDir())

			if err := os.WriteFile("go.mod", []byte("module example\n\ngo 1.27.1\n"), 0o600); err != nil {
				t.Fatal(err)
			}

			if err := os.WriteFile(scenario.filename, []byte(scenario.source), 0o600); err != nil {
				t.Fatal(err)
			}

			err := run(context.Background(), nil)
			if (err != nil) != scenario.fails {
				t.Fatalf("run error = %v, want failure %v", err, scenario.fails)
			}
		})
	}
}

// TestCheckFile covers the rule's positive matches and syntax/type boundaries.
//
//nolint:funlen // Keep the decision table together for review of false positives.
func TestCheckFile(t *testing.T) {
	cases := []struct {
		name  string
		lines []string
		match bool
	}{
		{
			name: "declaration",
			lines: []string{
				`m := make(map[string]int)`, "", `delete(m, "key")`,
			},
			match: true,
		},
		{
			name: "reassignment",
			lines: []string{
				`m := make(map[string]int)`, `m = make(map[string]int)`, "", `delete(m, "key")`,
			},
			match: true,
		},
		{
			name: "multiassignment",
			lines: []string{
				`m, n := make(map[string]int), make(map[string]int)`, "", `delete(n, "key")`, `_ = m`,
			},
			match: true,
		},
		{
			name: "multiple whitespace lines",
			lines: []string{
				`m := make(map[string]int)`, "\t ", "", `delete(m, "key")`,
			},
			match: true,
		},
		{
			name: "already compact",
			lines: []string{
				`m := make(map[string]int)`, `delete(m, "key")`,
			},
		},
		{
			name: "different variable",
			lines: []string{
				`m := make(map[string]int)`, `n := make(map[string]int)`, "", `delete(m, "key")`, `_ = n`,
			},
		},
		{
			name: "intervening statement",
			lines: []string{
				`m := make(map[string]int)`, `println("phase")`, "", `delete(m, "key")`,
			},
		},
		{
			name: "comment boundary",
			lines: []string{
				`m := make(map[string]int)`, "", "// Another phase.", `delete(m, "key")`,
			},
		},
		{
			name: "trailing comment boundary",
			lines: []string{
				`m := make(map[string]int) // Explain initialization.`, "", `delete(m, "key")`,
			},
		},
		{
			name: "shadowed delete",
			lines: []string{
				`delete := func(map[string]int, string) {}`, `m := make(map[string]int)`, "", `delete(m, "key")`,
			},
		},
		{
			name: "nested block",
			lines: []string{
				`if true {`, `m := make(map[string]int)`, "", `delete(m, "key")`, `}`,
			},
			match: true,
		},
		{
			name: "switch case",
			lines: []string{
				`switch { case true:`, `m := make(map[string]int)`, "", `delete(m, "key")`, `}`,
			},
			match: true,
		},
		{
			name: "select case",
			lines: []string{
				`select { default:`, `m := make(map[string]int)`, "", `delete(m, "key")`, `}`,
			},
			match: true,
		},
		{
			name: "blank line inside raw literal only",
			lines: []string{
				"m := map[string]string{\"key\": `first\n\nlast`}", `delete(m, "key")`,
			},
		},
	}
	for _, scenario := range cases {
		t.Run(scenario.name, func(t *testing.T) {
			source := "package example\nfunc example() {\n" + strings.Join(scenario.lines, "\n") + "\n}\n"

			findings := checkSource(t, source)
			if (len(findings) != 0) != scenario.match {
				t.Fatalf("match = %v, want %v; positions: %v", len(findings) != 0, scenario.match, findings)
			}

			for _, position := range findings {
				line := strings.Split(source, "\n")[position.Line-1]
				if strings.TrimSpace(line) != "" || position.Column != 1 {
					t.Fatalf("finding does not identify a blank line: %v: %q", position, line)
				}
			}
		})
	}
}

func TestPhysicalPositions(t *testing.T) {
	source := "package example\n//line virtual.go:100\nfunc example() {\n" +
		"m := make(map[string]int)\n\ndelete(m, \"key\")\n}\n"
	for _, ending := range []string{"\n", "\r\n"} {
		findings := checkSource(t, strings.ReplaceAll(source, "\n", ending))
		if len(findings) != 1 || findings[0].Line != 5 || findings[0].Filename != "example.go" {
			t.Fatalf("wrong physical position for line ending %q: %v", ending, findings)
		}
	}
}

func checkSource(t *testing.T, source string) []token.Position {
	t.Helper()

	fset := token.NewFileSet()

	file, err := parser.ParseFile(fset, "example.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	info := &types.Info{
		Defs: make(map[*ast.Ident]types.Object),
		Uses: make(map[*ast.Ident]types.Object),
	}
	config := &types.Config{}

	if _, err := config.Check("example", fset, []*ast.File{file}, info); err != nil {
		t.Fatal(err)
	}

	return checkFile(fset, file, info, []byte(source))
}
