#!/usr/bin/env python3
"""Generate the RHWA operator-upgrade status page from GitHub and Prow."""

import datetime
import json
import os
import sys
import urllib.error
import urllib.request


GITHUB_API = "https://api.github.com"
PROW_BUCKET = "https://storage.googleapis.com/origin-ci-test/pr-logs/directory"
NHC_JOB = (
    "pull-ci-medik8s-node-healthcheck-operator-medik8s-5.0-"
    "5.0-e2e-system-tests-nhc-operator-upgrade"
)

OPERATORS = [
    ("NHC", "medik8s/node-healthcheck-operator", 430, "medik8s/system-tests", 113),
    ("MDR", "medik8s/machine-deletion-remediation", 191, "medik8s/system-tests", 99),
    ("SBR", "medik8s/storage-based-remediation", 95, "medik8s/system-tests", 101),
    ("NMO", "medik8s/node-maintenance-operator", 183, "medik8s/system-tests", 100),
    ("FAR", "medik8s/fence-agents-remediation", 220, None, None),
    ("SNR", None, None, None, None),
]


def request(url, *, parse_json=False):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "system-tests-wiki"}
    token = os.environ.get("GH_TOKEN")
    if token and url.startswith(GITHUB_API):
        headers["Authorization"] = f"Bearer {token}"

    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=20) as response:
            body = response.read().decode().strip()
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError):
        return None

    return json.loads(body) if parse_json else body


def pull_request(repo, number):
    if not repo or not number:
        return None

    return request(f"{GITHUB_API}/repos/{repo}/pulls/{number}", parse_json=True)


def pr_cell(repo, number, pr):
    if not repo or not number:
        return "Not established"

    url = f"https://github.com/{repo}/pull/{number}"
    if not pr:
        return f"[#{number}]({url}) (status unavailable)"

    state = "merged" if pr.get("merged_at") else pr.get("state", "unknown").lower()
    if pr.get("draft") and state == "open":
        state = "open draft"

    base = pr.get("base", {}).get("ref")
    suffix = f", targets `{base}`" if base else ""

    return f"[#{number}]({url}), {state}{suffix}"


def prow_result(job):
    latest = request(f"{PROW_BUCKET}/{job}/latest-build.txt")
    history = f"https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/{job}"
    if not latest:
        return "No completed run yet", history

    finished = request(f"{PROW_BUCKET}/{job}/{latest}/finished.json", parse_json=True)
    if not finished:
        return f"Build {latest}: result unavailable", history

    result = finished.get("result") or ("SUCCESS" if finished.get("passed") else "FAILURE")
    timestamp = finished.get("timestamp")
    date = datetime.datetime.fromtimestamp(timestamp, datetime.UTC).date().isoformat() if timestamp else "unknown date"

    return f"{result.title()} ({date}, build {latest})", history


def generate():
    today = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
    prs = {}
    for _, source_repo, source_number, test_repo, test_number in OPERATORS:
        prs[(source_repo, source_number)] = pull_request(source_repo, source_number)
        prs[(test_repo, test_number)] = pull_request(test_repo, test_number)

    release_pr = pull_request("openshift/release", 84788)
    prow_status, prow_history = prow_result(NHC_JOB)

    lines = [
        "# RHWA OpenShift 5 operator upgrade status",
        "",
        f"Automatically refreshed: **{today}**",
        "",
        "This page is regenerated by the `system-tests` scheduled workflow. GitHub PR states and the latest durable Prow result update automatically. A green source-level upgrade does not mean the downstream customer upgrade has passed.",
        "",
        "## Representative-sample progress",
        "",
        "| Operator | Version source PR | system-tests PR | Dedicated CI | Local source upgrade | PR-candidate CI |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for name, source_repo, source_number, test_repo, test_number in OPERATORS:
        source = pr_cell(source_repo, source_number, prs[(source_repo, source_number)])
        test = pr_cell(test_repo, test_number, prs[(test_repo, test_number)])
        if name == "NHC":
            ci = pr_cell("openshift/release", 84788, release_pr)
            ci += f"; [Prow history]({prow_history})"
            local = "Passed twice on OpenShift 5.0.0-ec.5 (2026-09-09)"
            candidate = prow_status
        else:
            ci = "Not established"
            local = "Not assessed in the NHC representative sample"
            candidate = "Not run"

        lines.append(f"| {name} | {source} | {test} | {ci} | {local} | {candidate} |")

    lines.extend([
        "",
        "## Product-qualification progress",
        "",
        "These checks stay separate so upstream evidence cannot be mistaken for downstream release qualification.",
        "",
        "| Operator | Fresh source install on OpenShift 5 | Released 4.22 operator survives 4.22 → 5.0 | Red Hat catalog upgrade on 5.0 | Fresh downstream install on 5.0 |",
        "| --- | --- | --- | --- | --- |",
    ])
    for name, *_ in OPERATORS:
        status = "Deferred until the representative sample is accepted" if name == "NHC" else "Not run"
        lines.append(f"| {name} | Not run | {status} | {status} | {status} |")

    lines.extend([
        "",
        "## What the NHC test actually does",
        "",
        "The independently selectable `tier:upgrade-operator` Ginkgo test installs pinned older SNR and NHC bundles, creates a safe NHC configuration, verifies the old controller, upgrades in place to the PR-built candidate bundle, verifies the new version/image/pods, proves the same configuration survived and was reconciled, and cleans up only resources owned by that run.",
        "",
        "The local result is from the actual automated test, not a manual simulation. The final CI proof must run the dedicated job on NHC source PR #430 so Prow supplies that PR's temporary operator and bundle images.",
        "",
        "## Current blocker",
        "",
        "The representative test and job are in draft PRs. The Prow rehearsal is in progress. Downstream builds, catalogs, the 4.22-to-5.0 cluster upgrade, and downstream fresh install are tracked separately and do not require publishing NHC 5.8 to complete this upstream checkpoint.",
        "",
    ])

    return "\n".join(lines)


if __name__ == "__main__":
    output = generate()
    if len(sys.argv) == 2:
        with open(sys.argv[1], "w", encoding="utf-8") as output_file:
            output_file.write(output)
    else:
        print(output, end="")
